<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>PkgEditor</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Authors>mrdude2478</Authors>
    <Company>Maxton</Company>
    <Description>Windows Forms package editor for PS4/PS5 PFS/PKG files.</Description>
    <Version>0.2.0</Version>
    <FileVersion>0.2.0.0</FileVersion>
    <AssemblyVersion>0.2.0.0</AssemblyVersion>
    <Copyright>Copyright © 2018-2020 Maxton</Copyright>
    <ComVisible>false</ComVisible>
    <ApplicationIcon>pkgtool.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="LogWindow.cs" />
    <Compile Include="LogWindow.Designer.cs" />
    <Compile Include="MainWin.cs" />
    <Compile Include="MainWin.Designer.cs" />
    <Compile Include="PasscodeEntry.cs" />
    <Compile Include="PasscodeEntry.Designer.cs" />
    <Compile Include="KeyDB.cs" />
    <Compile Include="Program.cs" />
    <Compile Include="ValidationDialog.cs" />
    <Compile Include="ValidationDialog.Designer.cs" />
    <Compile Include="Views\CryptoDebug.cs" />
    <Compile Include="Views\CryptoDebug.Designer.cs" />
    <Compile Include="Views\FileView.cs" />
    <Compile Include="Views\FileView.Designer.cs" />
    <Compile Include="Views\PFSView.cs" />
    <Compile Include="Views\PFSView.Designer.cs" />
    <Compile Include="Views\SFOView.cs" />
    <Compile Include="Views\SFOView.Designer.cs" />
    <Compile Include="Views\GP4View.cs" />
    <Compile Include="Views\GP4View.Designer.cs" />
    <Compile Include="Views\PkgView.cs" />
    <Compile Include="Views\PkgView.Designer.cs" />
    <Compile Include="Views\ObjectView.cs" />
    <Compile Include="Views\ObjectView.Designer.cs" />
    <Compile Include="Views\View.cs" />
    <Compile Include="Properties\Resources.Designer.cs" />
    <Compile Include="Properties\Settings.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="LogWindow.resx" />
    <EmbeddedResource Include="MainWin.resx" />
    <EmbeddedResource Include="PasscodeEntry.resx" />
    <EmbeddedResource Include="Properties\Resources.resx" />
    <EmbeddedResource Include="ValidationDialog.resx" />
    <EmbeddedResource Include="Views\CryptoDebug.resx" />
    <EmbeddedResource Include="Views\FileView.resx" />
    <EmbeddedResource Include="Views\PFSView.resx" />
    <EmbeddedResource Include="Views\SFOView.resx" />
    <EmbeddedResource Include="Views\GP4View.resx" />
    <EmbeddedResource Include="Views\PkgView.resx" />
    <EmbeddedResource Include="Views\ObjectView.resx" />
  </ItemGroup>

  <ItemGroup>
    <None Include="app.config" />
    <None Include="pkgtool.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibOrbisPkg\LibOrbisPkg.csproj" />
  </ItemGroup>

</Project>
