<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>LibOrbisPkg</RootNamespace>
    <AssemblyName>LibOrbisPkg</AssemblyName>
    <LangVersion>7.3</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Authors>mrdude2478</Authors>
    <Company>Maxton</Company>
    <Description>Library for reading and building PS4/PS5 PFS/PKG archives.</Description>
    <Version>0.2.0</Version>
    <FileVersion>0.2.0.0</FileVersion>
    <AssemblyVersion>0.2.0.0</AssemblyVersion>
    <Copyright>Copyright © 2018-2020 Maxton</Copyright>
    <ComVisible>false</ComVisible>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="GP4\Gp4Creator.cs" />
    <Compile Include="GP4\Gp4Project.cs" />
    <Compile Include="GP4\Gp4Validator.cs" />
    <Compile Include="PFS\PFSCReader.cs" />
    <Compile Include="PFS\PFSCWriter.cs" />
    <Compile Include="PFS\PfsReader.cs" />
    <Compile Include="PFS\XtsDecryptReader.cs" />
    <Compile Include="PKG\Entry.cs" />
    <Compile Include="PKG\Enums.cs" />
    <Compile Include="PKG\PkgBuilder.cs" />
    <Compile Include="PFS\FlatPathTable.cs" />
    <Compile Include="PFS\FSTree.cs" />
    <Compile Include="PFS\PFSBuilder.cs" />
    <Compile Include="PFS\PfsProperties.cs" />
    <Compile Include="PFS\PfsStructs.cs" />
    <Compile Include="PKG\Pkg.cs" />
    <Compile Include="PKG\PkgProperties.cs" />
    <Compile Include="PKG\PkgReader.cs" />
    <Compile Include="PKG\PkgValidator.cs" />
    <Compile Include="PKG\PkgWriter.cs" />
    <Compile Include="PlayGo\ChunkDat.cs" />
    <Compile Include="PlayGo\Manifest.cs" />

    <Compile Include="Rif\LicenseDat.cs" />
    <Compile Include="Rif\LicenseInfo.cs" />
    <Compile Include="SFO\ParamSfo.cs" />
    <Compile Include="Util\Crypto.cs" />
    <Compile Include="Util\Extensions.cs" />
    <Compile Include="Util\Keys.cs" />
    <Compile Include="Util\MemoryMapped.cs" />
    <Compile Include="Util\MersenneTwister.cs" />
    <Compile Include="Util\OffsetStream.cs" />
    <Compile Include="Util\ReaderBase.cs" />
    <Compile Include="Util\StreamExtensions.cs" />
    <Compile Include="Util\SubStream.cs" />
    <Compile Include="Util\WriterBase.cs" />
    <Compile Include="Util\XtsBlockTransform.cs" />
  </ItemGroup>

</Project>
