<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <!-- Ensure RootNamespace and AssemblyName are explicitly specified -->
    <RootNamespace>LibOrbisPkgTests</RootNamespace>
    <AssemblyName>LibOrbisPkgTests</AssemblyName>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Authors>mrdude2478</Authors>
    <Company>Maxton</Company>
    <Description>Unit tests for LibOrbisPkg.</Description>
    <Version>0.2.0</Version>
    <FileVersion>1.0.0.0</FileVersion>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.2.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.3.2" />
    <PackageReference Include="MSTest.TestFramework" Version="3.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibOrbisPkg\LibOrbisPkg.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="PfsReaderTests.cs" />
    <Compile Include="PfsBuildTests.cs" />
    <Compile Include="PkgBuildTest.cs" />
    <Compile Include="PkgReadTest.cs" />
    <Compile Include="SfoTest.cs" />
    <Compile Include="TempDir.cs" />
    <Compile Include="TempFile.cs" />
    <Compile Include="TestHelper.cs" />
    <Compile Include="XtsTest.cs" />

  </ItemGroup>

</Project>
