<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <StartupObject>PkgTool.Program</StartupObject>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\PkgTool\Program.cs" Link="Program.cs" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibOrbisPkg.Core\LibOrbisPkg.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>
